import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useInView } from "react-intersection-observer";
import thumbGaming from "@/assets/thumb-gaming.jpg";
import thumbFinance from "@/assets/thumb-finance.jpg";
import thumbTech from "@/assets/thumb-tech.jpg";
import thumbFitness from "@/assets/thumb-fitness.jpg";

const categories = ["All", "Finance", "Gaming", "Tech", "Fitness", "Travel"] as const;

const examples = [
  { img: thumbFinance, category: "Finance", prompt: "Shocked face looking at stock charts going up" },
  { img: thumbGaming, category: "Gaming", prompt: "Epic gaming battle scene with neon glow" },
  { img: thumbTech, category: "Tech", prompt: "Futuristic laptop with holographic display" },
  { img: thumbFitness, category: "Fitness", prompt: "Dramatic transformation before and after" },
  { img: thumbFinance, category: "Finance", prompt: "Crypto portfolio hitting $1M milestone" },
  { img: thumbGaming, category: "Gaming", prompt: "Minecraft castle at sunset with dramatic lighting" },
  { img: thumbTech, category: "Tech", prompt: "iPhone 16 unboxing with cinematic lighting" },
  { img: thumbFitness, category: "Fitness", prompt: "30 day workout challenge results" },
  { img: thumbFinance, category: "Finance", prompt: "Passive income strategy breakdown" },
  { img: thumbGaming, category: "Gaming", prompt: "Fortnite victory royale celebration" },
  { img: thumbTech, category: "Tech", prompt: "AI robot assistant demo showcase" },
  { img: thumbFitness, category: "Fitness", prompt: "Morning routine of a bodybuilder" },
];

const ExampleGallery = () => {
  const [activeTab, setActiveTab] = useState<string>("All");
  const [visible, setVisible] = useState(8);
  const { ref, inView } = useInView({ triggerOnce: true, threshold: 0.1 });

  const filtered = activeTab === "All" ? examples : examples.filter((e) => e.category === activeTab);

  return (
    <section id="examples" className="py-24 bg-background" ref={ref}>
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 60 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <h2 className="text-4xl md:text-6xl font-display font-bold mb-4">
            Real thumbnails.{" "}
            <span className="gradient-text">Real results.</span>
          </h2>
          <p className="text-muted-foreground">Generated by ThumbAI creators</p>
        </motion.div>

        {/* Filter tabs */}
        <div className="flex items-center justify-center gap-2 mb-10 flex-wrap relative">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => { setActiveTab(cat); setVisible(8); }}
              className={`relative px-5 py-2 text-sm rounded-full transition-all duration-300 ${
                activeTab === cat
                  ? "text-primary-foreground"
                  : "text-muted-foreground hover:text-foreground bg-muted border border-border"
              }`}
              style={activeTab === cat ? { background: "linear-gradient(135deg, #8B47FF, #6366F1, #4F46E5)" } : {}}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 gap-4 space-y-4">
          <AnimatePresence mode="popLayout">
            {filtered.slice(0, visible).map((ex, i) => (
              <motion.div
                key={`${ex.prompt}-${i}`}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ duration: 0.4, delay: (i % 4) * 0.08 }}
                className="break-inside-avoid group relative rounded-xl overflow-hidden border border-border cursor-pointer"
              >
                <img
                  src={ex.img}
                  alt={ex.prompt}
                  className="w-full aspect-video object-cover transition-transform duration-500 group-hover:scale-105"
                  loading="lazy"
                />
                <div className="absolute top-2 left-2">
                  <span className="px-2 py-0.5 text-xs font-semibold rounded-full text-primary-foreground" style={{ background: "rgba(139,71,255,0.85)" }}>
                    {ex.category}
                  </span>
                </div>
                <div className="absolute inset-0 bg-[rgba(139,71,255,0.85)] backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-all duration-300 flex flex-col items-center justify-center p-4">
                  <p className="text-sm text-white text-center font-medium mb-3">
                    "{ex.prompt}"
                  </p>
                  <span className="px-4 py-1.5 rounded-full bg-white text-primary text-xs font-semibold">
                    Recreate Similar →
                  </span>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>

        {visible < filtered.length && (
          <div className="text-center mt-10">
            <button
              onClick={() => setVisible(filtered.length)}
              className="border border-[#D4C8FF] text-muted-foreground hover:border-primary hover:text-primary rounded-full px-8 py-3 font-medium transition-all duration-300"
            >
              Load More
            </button>
          </div>
        )}
      </div>
    </section>
  );
};

export default ExampleGallery;
